########
# Docker image optional for dev environment to do in container debug of source code
########
FROM node:14-buster-slim As Stage1

ARG BUILD_ID
ENV BUILD_ID=$BUILD_ID

LABEL stage=Stage1
LABEL build=$BUILD_ID

ENV NODE_ENV=production \
    PROJECT_HOME=/usr/app/ \
    DEBUG="app:*" \
    BUILD_DEPS="git python build-essential"

# create project home
RUN mkdir -p ${PROJECT_HOME}

# switch to working directory
WORKDIR ${PROJECT_HOME}

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ${PROJECT_HOME}

# install deps
RUN apt-get update > /dev/null \
    && apt-get install -y -qq --no-install-recommends ${BUILD_DEPS} \
    vim curl > /dev/null

#npm install
RUN npm i -g npm@6 \
    && npm install --quiet

# copy source code and run the build
COPY . $PROJECT_HOME

RUN npm run build

#cleanup
RUN apt-get purge -y ${BUILD_DEPS} > /dev/null \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 80 443 8080

# start the application
CMD ["pm2-runtime","process.yml"]