const envs: any = process.env;

interface IAws {
  REGION: string;
  DYNAMODB_ACCESS_KEY: string;
  DYNAMODB_SECRET_KEY: string;
  COGNITO_ACCESS_KEY: string;
  COGNITO_SECRET_KEY: string;
  COGNITO_APP_CLIENT_ID: string;
  COGNITO_INTERNAL_USER_POOL_ID: string;
  S3_STATIC_BUCKET: string;
  S3_STATIC_BUCKET_URL: string;
  S3_ACCESS_KEY: string;
  S3_SECRET_KEY: string;
  SES_ACCESS_KEY: string;
  SES_SECRET_KEY: string;
  SES_FROM_EMAIL: string;
  DYNAMODB_TABLE_PRIFIX: string;
  SNS_ACCESS_KEY: string;
  SNS_SECRET_KEY: string;
}

export const AWS_CONFIGS: IAws = Object.freeze({
  REGION: envs.AWS_REGION,
  DYNAMODB_ACCESS_KEY: envs.DYNAMODB_ACCESS_KEY,
  DYNAMODB_SECRET_KEY: envs.DYNAMODB_SECRET_KEY,
  COGNITO_ACCESS_KEY: envs.COGNITO_ACCESS_KEY,
  COGNITO_SECRET_KEY: envs.COGNITO_SECRET_KEY,
  COGNITO_APP_CLIENT_ID: envs.COGNITO_APP_CLIENT_ID,
  COGNITO_INTERNAL_USER_POOL_ID: envs.COGNITO_INTERNAL_USER_POOL_ID,
  S3_STATIC_BUCKET: envs.S3_STATIC_BUCKET,
  S3_STATIC_BUCKET_URL: envs.S3_STATIC_BUCKET_URL,
  S3_ACCESS_KEY: envs.S3_ACCESS_KEY,
  S3_SECRET_KEY: envs.S3_SECRET_KEY,
  SES_ACCESS_KEY: envs.SES_ACCESS_KEY,
  SES_SECRET_KEY: envs.SES_SECRET_KEY,
  SES_FROM_EMAIL: envs.SES_FROM_EMAIL,
  DYNAMODB_TABLE_PRIFIX: envs.DYNAMODB_TABLE_PRIFIX,
  SNS_ACCESS_KEY: envs.SNS_ACCESS_KEY,
  SNS_SECRET_KEY: envs.SNS_SECRET_KEY
});
