interface IMODELS {
  ACCOUNT: {
    ENTITY_TYPE: string;
    ENTITY: string;
    ENTITY_META: string;
    USER_TYPE: string;
    USER_ENTITY_MAPPER: string;
    PARENT_CHILD_MAPPER: string;
    USER_MASTER_USR: string;
    USER_MASTER_CHILD_USR: string;
    ENTITY_PACKAGE: string;
  };
  DIAGNOSTIC: {
    USER_ANIMAL: string;
    MASTER_ANIMAL: string;
    USER_PATHWAY: string;
    MASTER_PATHWAY: string;
    USER_SKILL: string;
    MASTER_SKILL: string;
    USER_ACTIVITY: string;
  };
  LC: {
    CSMP_CSP: string;
    TRAINING_MASTER_TOPIC: string;
    COUNSELOR_AVAILABILITY: string;
    SESSION_DESCRIPTION: string;
    MASTER_TEST: string;
    COUNSELOR_SCREEN: string;
    MASTER_SCREENING_STATUS: string;
    COUNSELOR_PROFILE: string;
    COUNSELOR_MASTER_ACTIVATION: string;
    COUNSELOR_INTERVIEW: string;
    COUNSELOR_MOCKSESSION: string;
    EXPERTISE: string;
    QUALIFICATION: string;
    LANGUAGE: string;
    CERTIFICATION: string;
    COUNSELOR_CERTIFICATION: string;
    COUNSELOR_QUALIFICATION: string;
    COUNSELOR_LANGUAGE: string;
    COUNSELOR_EXPERTISE: string;
    COUNSELOR_DOCUMENTS: string;
    COUNSELOR_PAYMENT_PROFILE: string;
    MASTER_SUB_AGENDA: string;
    MASTER_AGENDA: string;
    USER_MASTER_PLANAGENDAMAPPER: string;
    USER_SESSION_SCHEDULE: string;
    USER_SESSION_LOG: string;
    CSP: string;
    USER_FEEDBACK: string;
    SESSION_ACTION_PLAN: string;
    SESSION_TASKS: string;
    SESSION_IGNITOR_REPORT: string;
    FEEDBACK_RATING_OPTIONS_MAPPER: string;
    FEEDBACK_RATING: string;
    MASTERPAYROLL: string;
    COUNSELORPAYROLLMAPPER: string;
    COUNSELOR_INACTIVE_REASON: string;
    COUNSELOR_STATUS_MAPPER: string;
    INTERVIEWER: string;
    COUNSELOR_INTERVIEW_FEEDBACK: string;
    DOCUMENT: string;
    MASTER_PARAMETER: string;
    COUNSELOR_SCORE: string;
    MASTER_TOPIC: string;
    MASTER_ITEM: string;
    SESSION_SUBSCRIBE: string;
    ENTITY_ITEMMAPPER: string;
    COUNSELOR_ITEMMAPPER: string;
    COUNSELOR_OVERRIDE: string;
    UNIVERSAL_OVERRIDE: string;
    COUNSELOR_MASTER_AGREEMENT: string;
    COUNSELOR_AGREEMENT: string;
    UNIVERSAL_WORKING_HOURS: string;
  };
  SM: {
    USER_ASSOCIATE_SUBSCRIPTION: string;
    USER_CHECKOUT_SUBSCRIPTION: string;
    MASTER_PLAN: string;
    MASTER_PLANMETA: string;
  };
  CR: {
    OCCUPATION: string;
    OCCUPATION_META: string;
    COURSE: string;
    COURSE_META: string;
  };
  LH: {
    USER_USR_ASSOCIATECOURSE: string;
    USER_CHECKOUT_COURSES: string;
    COURSE_MASTER_DETAILS: string;
    USER_PACKAGE_SHIPPING: string;
    PUBLISHER_MASTER_DETAILS: string;
    HARDWARE_MASTER_ITEM: string;
  };
  WEB_ADMIN: {
    GLOBAL_MASTER_ROLE: string;
    GLOBAL_SYSTEM_APIS: string;
    GLOBAL_SYSTEM_ROLE_APIS_MAPPER: string;
    GLOBAL_MASTER_ROUTES: string;
    GLOBAL_USR_ROUTEROLE: string;
    GLOBAL_BLOGS_VIDEOS: string;
    USER_MASTER_USR: string;
    USER_USR_ROLE: string;
    GLOBAL_MASTER_REGION: string;
    GLOBAL_MASTER_CITY: string;
    GLOBAL_MASTER_VPA: string;
    GLOBAL_MASTER_COUPON: string;
    GLOBAL_REGION_OFFER_SMAPPER: string;
    GLOBAL_MASTER_STATE: string;
    GLOBAL_REGION_COUPON_MAPPER: string;
    GLOBAL_USER_VPA_MAPPER: string;
    GLOBAL_CARD_PT_OFFERING_MAPPER: string;
    GLOBAL_CARD_SALES_ALLOCATION: string;
    GLOBAL_MASTER_TRANSACTION: string;
    GLOBAL_PLATFORM_OFFERING: string;
    GLOBAL_SALES_DEPOSIT: string;
    GLOBAL_SALES_METADATA: string;
    CS_MEMBERSHIP: string;
    GLOBAL_COUPON_PLATFORM_OFFERING: string;
    GLOBAL_MASTER_BANNER_SECTION: string;
    GLOBAL_MASTER_TESTIMONIAL: string;
    GLOBAL_MASTER_SERVICES: string;
  };
  SA: {
    CG_MASTER_CG: string;
    CG_MASTER_META: string;
  };
}

export const MODELS: IMODELS = Object.freeze({
  ACCOUNT: {
    ENTITY_TYPE: 'EntityType',
    ENTITY: 'Entity',
    ENTITY_META: 'EntityMeta',
    USER_TYPE: 'UserType',
    USER_ENTITY_MAPPER: 'UserEntityMapper',
    PARENT_CHILD_MAPPER: 'ParentChildMapper',
    USER_MASTER_USR: 'UserMasterUsr',
    USER_MASTER_CHILD_USR: 'UserMasterChildUsr',
    ENTITY_PACKAGE: 'EntityPackage'
  },
  DIAGNOSTIC: {
    USER_ANIMAL: 'UserAnimal',
    MASTER_ANIMAL: 'MasterAnimal',
    USER_PATHWAY: 'UserPathway',
    MASTER_PATHWAY: 'MasterPathway',
    USER_SKILL: 'UserSkill',
    MASTER_SKILL: 'MasterSkill',
    USER_ACTIVITY: 'UserActivity'
  },
  LC: {
    CSMP_CSP: 'CsmpCsp',
    CSP: 'CSP',
    TRAINING_MASTER_TOPIC: 'TrainingMasterTopic',
    ENTITY_ITEMMAPPER: 'EntityItemMapper',
    COUNSELOR_OVERRIDE: 'CounselorOverride',
    SESSION_DESCRIPTION: 'SessionDescription',
    COUNSELOR_ITEMMAPPER: 'CounselorItemMapper',
    COUNSELOR_AVAILABILITY: 'CounselorAvailability',
    MASTER_TEST: 'MasterTest',
    COUNSELOR_PROFILE: 'CounselorProfile',
    COUNSELOR_MASTER_ACTIVATION: 'CounselorMasterActivation',
    COUNSELOR_INTERVIEW: 'CounselorInterview',
    COUNSELOR_MOCKSESSION: 'CounselorMocksession',
    EXPERTISE: 'Expertise',
    QUALIFICATION: 'Qualification',
    LANGUAGE: 'Language',
    DOCUMENT: 'Document',
    CERTIFICATION: 'Certification',
    COUNSELOR_CERTIFICATION: 'CounselorCertification',
    COUNSELOR_QUALIFICATION: 'CounselorQualification',
    COUNSELOR_LANGUAGE: 'CounselorLanguage',
    COUNSELOR_EXPERTISE: 'CounselorExpertise',
    COUNSELOR_DOCUMENTS: 'CounselorDocuments',
    COUNSELOR_PAYMENT_PROFILE: 'CounselorPaymentProfile',
    MASTER_SUB_AGENDA: 'MasterSubAgenda',
    MASTER_AGENDA: 'MasterAgenda',
    USER_MASTER_PLANAGENDAMAPPER: 'UserMasterPlanagendaMapper',
    USER_SESSION_SCHEDULE: 'UserSessionSchedule',
    USER_SESSION_LOG: 'UserSessionLog',
    USER_FEEDBACK: 'UserFeedback',
    SESSION_ACTION_PLAN: 'SessionActionPlan',
    SESSION_TASKS: 'SessionTasks',
    SESSION_IGNITOR_REPORT: 'SessionIgnitorReport',
    FEEDBACK_RATING_OPTIONS_MAPPER: 'FeedbackRatingOptionsMapper',
    FEEDBACK_RATING: 'FeedbackRating',
    MASTERPAYROLL: 'MasterPayroll',
    COUNSELORPAYROLLMAPPER: 'CounselorPayrollMapper',
    COUNSELOR_INACTIVE_REASON: 'CounselorInactiveReason',
    COUNSELOR_STATUS_MAPPER: 'CounselorStatusMapper',
    MASTER_SCREENING_STATUS: 'MasterScreeningStatus',
    COUNSELOR_SCREEN: 'CounselorScreen',
    INTERVIEWER: 'Interviewer',
    COUNSELOR_INTERVIEW_FEEDBACK: 'CounselorInterviewFeedback',
    MASTER_PARAMETER: 'MasterInterview',
    COUNSELOR_SCORE: 'CounselorScoreTrace',
    MASTER_TOPIC: 'TrainingMasterTopic',
    MASTER_ITEM: 'MasterItem',
    SESSION_SUBSCRIBE: 'UserSessionSubscribe',
    UNIVERSAL_OVERRIDE: 'UniversalOverride',
    COUNSELOR_MASTER_AGREEMENT: 'CounselorMasterAgreement',
    COUNSELOR_AGREEMENT: 'CounselorAgreement',
    UNIVERSAL_WORKING_HOURS: 'UniversalWorkingHours'
  },
  SM: {
    MASTER_PLAN: 'MasterPlan',
    MASTER_PLANMETA: 'MasterPlanmeta',
    USER_ASSOCIATE_SUBSCRIPTION: 'UserAssociateSubscription',
    USER_CHECKOUT_SUBSCRIPTION: 'UserCheckoutSubscription'
  },
  CR: {
    OCCUPATION: 'Occupation',
    OCCUPATION_META: 'OccupationMeta',
    COURSE: 'Course',
    COURSE_META: 'CourseMeta'
  },
  LH: {
    USER_CHECKOUT_COURSES: 'UserCheckoutCourses',
    USER_USR_ASSOCIATECOURSE: 'UserUsrAssociatecourse',
    COURSE_MASTER_DETAILS: 'CourseMasterDetails',
    USER_PACKAGE_SHIPPING: 'UserPackageShipping',
    PUBLISHER_MASTER_DETAILS: 'PublisherMasterDetails',
    HARDWARE_MASTER_ITEM: 'HardwareMasterItem'
  },
  WEB_ADMIN: {
    GLOBAL_MASTER_ROLE: 'GlobalMasterRole',
    GLOBAL_SYSTEM_APIS: 'GlobalSystemApis',
    GLOBAL_SYSTEM_ROLE_APIS_MAPPER: 'GlobalSystemRoleApisMapper',
    GLOBAL_MASTER_ROUTES: 'GlobalMasterRoutes',
    GLOBAL_USR_ROUTEROLE: 'GlobalUsrRouteRole',
    GLOBAL_BLOGS_VIDEOS: 'GlobalBlogsVideos',
    USER_MASTER_USR: 'UserMasterUsr',
    USER_USR_ROLE: 'UserUsrRole',
    GLOBAL_MASTER_REGION: 'GlobalMasterRegion',
    GLOBAL_MASTER_CITY: 'GlobalMasterCity',
    GLOBAL_MASTER_VPA: 'GlobalMasterVpa',
    GLOBAL_MASTER_COUPON: 'GlobalMasterCoupon',
    GLOBAL_REGION_OFFER_SMAPPER: 'GlobalRegionOfferSmapper',
    GLOBAL_MASTER_STATE: 'GlobalMasterState',
    GLOBAL_REGION_COUPON_MAPPER: 'GlobalRegionCouponMapper',
    GLOBAL_USER_VPA_MAPPER: 'GlobalUserVpaMapper',
    GLOBAL_CARD_PT_OFFERING_MAPPER: 'GlobalCardPtOfferingMapper',
    GLOBAL_CARD_SALES_ALLOCATION: 'GlobalCardSalesAllocation',
    GLOBAL_MASTER_TRANSACTION: 'GlobalMasterTransaction',
    GLOBAL_PLATFORM_OFFERING: 'GlobalPlatformOffering',
    GLOBAL_SALES_DEPOSIT: 'GlobalSalesDeposit',
    GLOBAL_SALES_METADATA: 'GlobalSalesMetaData',
    CS_MEMBERSHIP: 'CsMemberShip',
    GLOBAL_COUPON_PLATFORM_OFFERING: 'GlobalCouponPlatformOffering',
    GLOBAL_MASTER_BANNER_SECTION: 'GlobalMasterBannerSection',
    GLOBAL_MASTER_TESTIMONIAL: 'GlobalMasterTestimonial',
    GLOBAL_MASTER_SERVICES: 'GlobalMasterServices'
  },
  SA: {
    CG_MASTER_CG: 'cgMastercg',
    CG_MASTER_META: 'cgMasterMeta'
  }
});
