interface ITABLES {
  ACCOUNT: {
    ENTITY_TYPE: string;
    ENTITY: string;
    ENTITY_META: string;
    USER_TYPE: string;
    USER_ENTITY_MAPPER: string;
    PARENT_CHILD_MAPPER: string;
    USER_MASTER_USR: string;
    USER_MASTER_CHILD_USR: string;
    ENTITY_PACKAGE: string;
  };
  DIAGNOSTIC: {
    USER_ANIMAL: string;
    MASTER_ANIMAL: string;
    USER_PATHWAY: string;
    MASTER_PATHWAY: string;
    USER_SKILL: string;
    MASTER_SKILL: string;
    USER_ACTIVITY: string;
  };
  LC: {
    CSMP_CSP: string;
    CSP: string;
    TRAINING_MASTER_TOPIC: string;
    COUNSELOR_AVAILABILITY: string;
    SESSION_DESCRIPTION: string;
    MASTER_TEST: string;
    COUNSELOR_SCREEN: string;
    MASTER_SCREENING_STATUS: string;
    COUNSELOR_INTERVIEW: string;
    COUNSELOR_MOCKSESSION: string;
    COUNSELOR_PROFILE: string;
    COUNSELOR_MASTER_ACTIVATION: string;
    EXPERTISE: string;
    QUALIFICATION: string;
    LANGUAGE: string;
    DOCUMENT: string;
    CERTIFICATION: string;
    COUNSELOR_CERTIFICATION: string;
    COUNSELOR_QUALIFICATION: string;
    COUNSELOR_LANGUAGE: string;
    COUNSELOR_EXPERTISE: string;
    COUNSELOR_DOCUMENTS: string;
    COUNSELOR_PAYMENT_PROFILE: string;
    MASTER_SUB_AGENDA: string;
    MASTER_AGENDA: string;
    USER_MASTER_PLANAGENDAMAPPER: string;
    USER_SESSION_SCHEDULE: string;
    USER_SESSION_LOG: string;

    USER_FEEDBACK: string;
    SESSION_ACTION_PLAN: string;
    SESSION_TASKS: string;
    SESSION_IGNITOR_REPORT: string;
    FEEDBACK_RATING_OPTIONS_MAPPER: string;
    FEEDBACK_RATING: string;
    MASTERPAYROLL: string;
    COUNSELORPAYROLLMAPPER: string;
    COUNSELOR_INACTIVE_REASON: string;
    COUNSELOR_STATUS_MAPPER: string;
    INTERVIEWER: string;
    COUNSELOR_INTERVIEW_FEEDBACK: string;
    MASTER_PARAMETER: string;
    COUNSELOR_SCORE: string;
    MASTER_TOPIC: string;
    MASTER_ITEM: string;
    SESSION_SUBSCRIBE: string;
    ENTITY_ITEMMAPPER: string;
    COUNSELOR_ITEMMAPPER: string;
    COUNSELOR_OVERRIDE: string;
    UNIVERSAL_OVERRIDE: string;
    COUNSELOR_MASTER_AGREEMENT: string;
    COUNSELOR_AGREEMENT: string;
    UNIVERSAL_WORKING_HOURS: string;
  };
  SM: {
    MASTER_PLAN: string;
    MASTER_PLANMETA: string;
    USER_ASSOCIATE_SUBSCRIPTION: string;
    USER_CHECKOUT_SUBSCRIPTION: string;
  };
  CR: {
    OCCUPATION: string;
    OCCUPATION_META: string;
    COURSE: string;
    COURSE_META: string;
  };
  LH: {
    USER_USR_ASSOCIATECOURSE: string;
    USER_CHECKOUT_COURSES: string;
    COURSE_MASTER_DETAILS: string;
    USER_PACKAGE_SHIPPING: string;
    PUBLISHER_MASTER_DETAILS: string;
    HARDWARE_MASTER_ITEM: string;
  };
  WEB_ADMIN: {
    CS_MEMBERSHIP: string;
    GLOBAL_MASTER_ROLE: string;
    GLOBAL_SYSTEM_APIS: string;
    GLOBAL_SYSTEM_ROLE_APIS_MAPPER: string;
    GLOBAL_MASTER_ROUTES: string;
    GLOBAL_USR_ROUTEROLE: string;
    GLOBAL_BLOGS_VIDEOS: string;
    USER_MASTER_USR: string;
    USER_USR_ROLE: string;
    GLOBAL_MASTER_REGION: string;
    GLOBAL_MASTER_CITY: string;
    GLOBAL_MASTER_VPA: string;
    GLOBAL_MASTER_COUPON: string;
    GLOBAL_REGION_OFFER_SMAPPER: string;
    GLOBAL_MASTER_STATE: string;
    GLOBAL_REGION_COUPON_MAPPER: string;
    GLOBAL_USER_VPA_MAPPER: string;
    GLOBAL_CARD_PT_OFFERING_MAPPER: string;
    GLOBAL_CARD_SALES_ALLOCATION: string;
    GLOBAL_MASTER_TRANSACTION: string;
    GLOBAL_PLATFORM_OFFERING: string;
    GLOBAL_SALES_DEPOSIT: string;
    GLOBAL_SALES_METADATA: string;
    GLOBAL_COUPON_PLATFORM_OFFERING: string;
    GLOBAL_MASTER_BANNER_SECTION: string;
    GLOBAL_MASTER_TESTIMONIAL: string;
    GLOBAL_MASTER_SERVICES: string;
  };
  SA: {
    CG_MASTER_CG: string;
    CG_MASTER_META: string;
  };
}

export const TABLES: ITABLES = Object.freeze({
  ACCOUNT: {
    ENTITY_TYPE: 'ac_global_master_entitytype',
    ENTITY: 'ac_global_master_entity',
    ENTITY_META: 'ac_global_master_entitymeta',
    USER_TYPE: 'ac_global_master_usertype',
    USER_ENTITY_MAPPER: 'ac_global_usr_userentitymapper',
    PARENT_CHILD_MAPPER: 'ac_global_usr_parentchildmapper',
    USER_MASTER_USR: 'ac_user_master_usr',
    USER_MASTER_CHILD_USR: 'ac_user_master_childusr',
    ENTITY_PACKAGE: 'ac_global_entity_entitypackage'
  },
  DIAGNOSTIC: {
    USER_ANIMAL: 'dt_behaviour_user_animal',
    MASTER_ANIMAL: 'dt_behaviour_master_animal',
    USER_PATHWAY: 'dt_interest_user_pathway',
    MASTER_PATHWAY: 'dt_interest_master_pathway',
    USER_SKILL: 'dt_skill_user_skill',
    MASTER_SKILL: 'dt_skill_master_skill',
    USER_ACTIVITY: 'dt_hhh_user_activity'
  },
  LC: {
    CSMP_CSP: 'lc_global_session_csmpcsp',
    CSP: 'lc_global_session_csp',
    TRAINING_MASTER_TOPIC: 'lc_training_master_topic',
    COUNSELOR_OVERRIDE: 'lc_user_counselor_override',
    COUNSELOR_AVAILABILITY: 'lc_user_counselor_availability',
    MASTER_TEST: 'lc_user_master_test',
    SESSION_DESCRIPTION: 'lc_global_master_sessiondesc',
    COUNSELOR_PROFILE: 'lc_user_counselor_profile',
    COUNSELOR_MASTER_ACTIVATION: 'lc_counselor_master_activation',
    COUNSELOR_INTERVIEW: 'lc_user_counselor_interview',
    COUNSELOR_MOCKSESSION: 'lc_user_counselor_mocksession',
    EXPERTISE: 'lc_global_master_expertise',
    DOCUMENT: 'lc_global_master_document',
    QUALIFICATION: 'lc_global_master_qualification',
    LANGUAGE: 'lc_global_master_language',
    CERTIFICATION: 'lc_global_master_certification',
    COUNSELOR_EXPERTISE: 'lc_user_counselor_expertise',
    COUNSELOR_QUALIFICATION: 'lc_user_counselor_qualification',
    COUNSELOR_LANGUAGE: 'lc_user_counselor_language',
    COUNSELOR_CERTIFICATION: 'lc_user_counselor_certification',
    COUNSELOR_DOCUMENTS: 'lc_user_counselor_documents',
    COUNSELOR_PAYMENT_PROFILE: 'lc_user_counselor_paymentprofile',
    MASTER_SUB_AGENDA: 'lc_global_master_subagenda',
    MASTER_AGENDA: 'lc_global_master_agenda',
    USER_MASTER_PLANAGENDAMAPPER: 'lc_global_master_planagendamapper',
    USER_SESSION_SCHEDULE: 'lc_global_session_schedule',
    USER_SESSION_LOG: 'lc_global_session_log',
    USER_FEEDBACK: 'lc_feedback_usr_feedback',
    SESSION_ACTION_PLAN: 'lc_global_session_actionplan',
    SESSION_TASKS: 'lc_global_session_tasks',
    SESSION_IGNITOR_REPORT: 'lc_global_session_ignitorreport',
    FEEDBACK_RATING_OPTIONS_MAPPER: 'lc_feedback_master_ratingoptionsmapper',
    FEEDBACK_RATING: 'lc_feedback_master_rating',
    MASTERPAYROLL: 'lc_user_master_payroll',
    COUNSELORPAYROLLMAPPER: 'lc_user_counselor_payrollmapper',
    COUNSELOR_INACTIVE_REASON: 'lc_global_master_counselor_inactive_reason',
    COUNSELOR_STATUS_MAPPER: 'lc_user_counselor_status_mapper',
    COUNSELOR_SCREEN: 'lc_user_counselor_screen',
    MASTER_SCREENING_STATUS: 'lc_user_master_screening_status',
    INTERVIEWER: 'lc_global_interviewer',
    COUNSELOR_INTERVIEW_FEEDBACK: 'lc_user_counselor_interview_feedback',
    MASTER_PARAMETER: 'lc_global_master_parameter',
    COUNSELOR_SCORE: 'lc_user_counselor_scoretrace',
    MASTER_TOPIC: 'lc_training_master_topic',
    MASTER_ITEM: 'lc_global_master_item',
    SESSION_SUBSCRIBE: 'lc_user_session_subscribe',
    ENTITY_ITEMMAPPER: 'lc_global_entity_itemmapper',
    COUNSELOR_ITEMMAPPER: 'lc_counselor_itemmapper',
    UNIVERSAL_OVERRIDE: 'lc_global_universal_override',
    COUNSELOR_MASTER_AGREEMENT: 'lc_counselor_master_agreement',
    COUNSELOR_AGREEMENT: 'lc_user_counselor_agreement',
    UNIVERSAL_WORKING_HOURS: 'lc_global_universal_workinghours'
  },
  SM: {
    MASTER_PLAN: 'sm_plan_master_plan',
    MASTER_PLANMETA: 'sm_plan_master_planmeta',
    USER_ASSOCIATE_SUBSCRIPTION: 'sm_user_usr_associatesubscription',
    USER_CHECKOUT_SUBSCRIPTION: 'sm_user_checkout_subscription'
  },
  CR: {
    OCCUPATION: 'cr_regional_master_occupation',
    OCCUPATION_META: 'cr_regional_master_occupationmeta',
    COURSE: 'cr_global_master_course',
    COURSE_META: 'cr_global_master_coursemeta'
  },
  LH: {
    USER_USR_ASSOCIATECOURSE: 'lh_user_usr_associatecourse',
    USER_CHECKOUT_COURSES: 'lh_user_checkout_courses',
    COURSE_MASTER_DETAILS: 'lc_course_master_details',
    USER_PACKAGE_SHIPPING: 'lh_user_package_shipping',
    PUBLISHER_MASTER_DETAILS: 'lc_publisher_master_details',
    HARDWARE_MASTER_ITEM: 'lh_hardware_master_item'
  },
  WEB_ADMIN: {
    CS_MEMBERSHIP: 'wa_global_cs_membership',
    GLOBAL_MASTER_ROLE: 'wa_global_master_role',
    GLOBAL_SYSTEM_APIS: 'wa_golbal_system_apis',
    GLOBAL_SYSTEM_ROLE_APIS_MAPPER: 'wa_global_system_role_apis_mapper',
    GLOBAL_MASTER_ROUTES: 'wa_global_master_routes',
    GLOBAL_USR_ROUTEROLE: 'wa_global_usr_routerole',
    GLOBAL_BLOGS_VIDEOS: 'wa_global_blogs_videos',
    USER_MASTER_USR: 'wa_user_master_usr',
    USER_USR_ROLE: 'wa_user_usr_role',
    GLOBAL_MASTER_REGION: 'wa_global_master_region',
    GLOBAL_MASTER_CITY: 'wa_global_master_city',
    GLOBAL_MASTER_VPA: 'wa_global_master_vpa',
    GLOBAL_MASTER_COUPON: 'wa_global_master_coupon',
    GLOBAL_REGION_OFFER_SMAPPER: 'Global_Region_Offer_Smapper',
    GLOBAL_MASTER_STATE: 'wa_global_master_state',
    GLOBAL_REGION_COUPON_MAPPER: 'wa_global_region_couponmapper',
    GLOBAL_USER_VPA_MAPPER: 'wa_global_user_vpamapper',
    GLOBAL_CARD_PT_OFFERING_MAPPER: 'wa_global_card_ptofferingmapper',
    GLOBAL_CARD_SALES_ALLOCATION: 'wa_global_card_salesallocation',
    GLOBAL_MASTER_TRANSACTION: 'wa_global_master_transaction',
    GLOBAL_PLATFORM_OFFERING: 'wa_global_platform_offering',
    GLOBAL_SALES_DEPOSIT: 'wa_global_sales_deposite',
    GLOBAL_SALES_METADATA: 'wa_global_sales_metadata',
    GLOBAL_COUPON_PLATFORM_OFFERING: 'wa_global_coupon_couponptoffering',
    GLOBAL_MASTER_BANNER_SECTION: 'wa_global_banner_section',
    GLOBAL_MASTER_TESTIMONIAL: 'wa_global_master_testimonial',
    GLOBAL_MASTER_SERVICES: 'wa_global_master_services'
  },
  SA: {
    CG_MASTER_CG: 'sa_cg_master_cg',
    CG_MASTER_META: 'sa_cg_master_cgmeta'
  }
});
